######################
### DESIGN CHANGES ###
######################

# statusbar
set -g status-right "#{prefix_highlight}#[fg=colour232,bg=colour231 bold] ♫ #{music_status} #{artist}: #{track}  |  %a %h-%d %H:%M  #[fg=colour238,bg=colour231]#[fg=colour233,bg=colour247]"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'robhurring/tmux-spotify'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# Initialize scroll mouse on tmux
setw -g mouse on
